-- Create the Sender table
CREATE TABLE IF NOT EXISTS sender (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matric VARCHAR(255),
    name VARCHAR(255),
    phone VARCHAR(255) UNIQUE,
    role VARCHAR(255)
);

-- Create the Staff table
CREATE TABLE IF NOT EXISTS staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    role VARCHAR(255)
);

-- Create the Parcel table
CREATE TABLE IF NOT EXISTS parcel (
    tracking_number INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weight INTEGER,
    sender_id BIGINT,
    delivery_status VARCHAR(255),
    order_date VARCHAR(255),
    payment_status VARCHAR(255),
    receiver_phone VARCHAR(255),
    sender_phone VARCHAR(255),
    FOREIGN KEY (sender_id) REFERENCES sender(id)
);

-- Insert sample data into the Sender table
INSERT INTO sender (name, matric, phone, role) VALUES
('Ahmad Bin Ali', 'M12345', '0111111111', 'ROLE_SENDER'),
('Siti Aisyah', 'M12346', '0122222222', 'ROLE_SENDER'),
('Muhammad Faiz', 'M12347', '0133333333', 'ROLE_SENDER');

-- Insert sample data into the Parcel table
INSERT INTO parcel (weight, sender_id, delivery_status, order_date, payment_status, receiver_phone, sender_phone) VALUES
(5, 1, 'Delivered', '2025-06-10', 'Paid', '0123456789', '0111111111'),
(10, 2, 'In Transit', '2025-06-11', 'Pending', '0123456790', '0122222222'),
(15, 3, 'Pending', '2025-06-12', 'Unpaid', '0123456791', '0133333333');

-- Insert staff login (password is plain here; should be BCrypted in production)
INSERT INTO staff (username, password, role) VALUES
('staff', 'staff123', 'ROLE_STAFF');
